spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_medico_prod?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
