server:
  port: 8083

spring:
  application:
    name: producto-service

  datasource:
    url: jdbc:mysql://localhost:3306/bd_producto
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
